name: Docker Build
on:
  workflow_dispatch:
    inputs: {}
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container
        run: |
          docker build -t ghcr.io/brunojppb/tie-spotter:latest .

      - name: login to Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push to Github Container Registry
        run: |
          docker push ghcr.io/brunojppb/tie-spotter:latest
