name: Docker Build
on:
  workflow_dispatch:
    inputs: {}
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: "linux/amd64"
          push: false
          tags: "brunojppb/tie-spotter:latest"

      - name: login to Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push to Github Container Registry
        run: |
          docker tag brunojppb/tie-spotter:latest ghcr.io/brunojppb/tie-spotter:latest
          docker push ghcr.io/brunojppb/tie-spotter:latest
